---
# Personal workspace setup automation.
# @file The git installation tasks list.
# @author Rodrigo Siqueira <me@rodriados.com>
# @copyright 2026-present Rodrigo Siqueira

- name: Install Git
  when: enable_installation.git | default(false)
  ignore_errors: true
  block:
    - name: Assert 'git.user_name'
      ansible.builtin.assert:
        that:
          - git.user_name | length > 0
        msg: "Must define git user name"
        quiet: true

    - name: Assert 'git.user_email'
      ansible.builtin.assert:
        that:
          - git.user_email | length > 0
          - git.user_email is match("^.*\@.*")
        msg: "Must define git user email"
        quiet: true

    - name: Configure Git User Name
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git.user_name }}"

    - name: Configure Git User Email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git.user_email }}"
