---
# Personal workspace setup automation.
# @file The minimal profile main tasks list.
# @author Rodrigo Siqueira <me@rodriados.com>
# @copyright 2026-present Rodrigo Siqueira

- name: Import Development Essentials Tasks
  ansible.builtin.include_tasks:
    file: essentials.yml
  when: essentials.install | default(false)
  tags: essentials

- name: Install Packages
  ansible.builtin.package:
    name: "{{ global + extras }}"
    state: present
  vars:
    global: "{{ default_packages | default([]) }}"
    extras: "{{ extra_packages | default([]) }}"
  become: true

- name: Import Git Tasks
  ansible.builtin.include_tasks:
    file: git.yml
  when: git.install | default(false)
  tags: git

- name: Install Terminal Tools
  ansible.builtin.include_tasks:
    file: terminal.yml
  tags: terminal

- name: Import Dotfiles Tasks
  ansible.builtin.include_tasks:
    file: dotfiles.yml
  when: dotfiles.install | default(false)
  tags: dotfiles
