---
# Personal workspace setup automation.
# @file The playbook to perform minimal system installation.
# @author Rodrigo Siqueira <me@rodriados.com>
# @copyright 2026-present Rodrigo Siqueira
- name: Workstation Setup
  hosts: local

  vars_files:
    - defaults/main.yml
    - [ overrides-minimal.yml, vars/overrides-minimal.yml, overrides.yml ]

  vars:
    ansible_user_home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Include Global Tasks
      ansible.builtin.include_tasks:
        file: tasks/main.yml
      tags: always

    - name: Include Role 'rodriados.minimal'
      ansible.builtin.include_role:
        name: rodriados.minimal
      tags: always
