---
# Personal workspace setup automation.
# @file The playbook to perform full personal system installation.
# @author Rodrigo Siqueira <me@rodriados.com>
# @copyright 2026-present Rodrigo Siqueira
- name: Workstation Setup
  hosts: local

  vars_files:
    - defaults/main.yml
    - [ overrides-personal.yml, vars/overrides-personal.yml, overrides.yml ]

  vars:
    ansible_user_home: "{{ lookup('env', 'HOME') }}"

  pre_tasks:
    - name: Execute Pre-Tasks
      ansible.builtin.include_tasks:
        file: tasks/pre-tasks.yml
      tags: always

  tasks:
    - name: Include Global Tasks
      ansible.builtin.include_tasks:
        file: tasks/main.yml
      tags: always

    - name: Include Role 'rodriados.personal'
      ansible.builtin.include_role:
        name: rodriados.personal
      tags: always
