---
# Personal workspace setup automation.
# @file The playbook pre-execution tasks list.
# @author Rodrigo Siqueira <me@rodriados.com>
# @copyright 2026-present Rodrigo Siqueira

- name: Install Dynamic Requirements
  ansible.builtin.command:
    cmd: "ansible-galaxy install -p roles -r {{ item }}"
  with_first_found:
    - files:
        - "requirements-{{ ansible_facts['distribution'] | lower }}.yml"
        - "requirements-{{ ansible_facts['os_family'] | lower }}.yml"
        - "requirements-{{ ansible_facts['system'] | lower }}.yml"
      paths:
        - files
      skip: true
