---
name: run-tests-lint

on: [push, pull_request]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install yamllint ansible-core ansible-lint

      - name: List target lint files
        run: yamllint --list-files .

      - name: Lint YAML code
        run: |
          yamllint .
          ansible-lint

      - name: Check playbook syntax
        run: ansible-playbook main.yml --syntax-check
